//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::auth_role::Entity as AuthRole;
pub use super::auth_user::Entity as AuthUser;
pub use super::link_user_role::Entity as LinkUserRole;
