[network]
host = "localhost"
port = 8080
prefix = "/api"
[database]
username = "postgres"
password = "postgres"
database = "web_tpl"
host = "localhost"
port = 5432
show_sql = true

[redis]
type = "Standalone"
node = "redis://localhost:6379"
[jwt]
header_name = "Authorization"
header_prefix = "Bearer "
issuer = "web-tpl"
secret = "KZLQ7e1R*OmK^s1Yi5qqqe5yhN9VaYbdqfOn*8CxoA"
expiration = 3600
anno_url = [
    "/api/login",
    "/api/demo01/{*p}",
    "/swagger-ui/{*p}",
    "/api-docs/openapi.json",
]
[cache]
prefix = "web-tpl:cache"
ttl = 3600
ttl_delta = 13
