debug = true

[network]
host = "localhost"
port = 8080
prefix = "/api"
[database]
username = "postgres"
password = "postgres"
database = "web_tpl"
host = "localhost"
port = 5432

[redis]
type = "Standalone"
node = "redis://localhost:6379"
[jwt]
issuer = "web-tpl"
secret = "secret"
expiration = 3600
