[package]
name = "db"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../common" }

serde = { workspace = true }
serde_json = { workspace = true }
sea-orm = {workspace = true}
utoipa = { workspace = true }
